# add makefile to the list, if makefile changed, still need to compile
457: 457.cpp makefile ../lib/tools.cpp ../lib/tools.h ../lib/int.h ../lib/int.cpp
	g++ -Wall -O3 457.cpp ../lib/tools.cpp ../lib/int.cpp -std=c++0x -o 457
