# add makefile to the list, if makefile changed, still need to compile
501: 501.cpp makefile ../lib/tools.cpp ../lib/tools.h 
	g++ -Wall -O3 501.cpp ../lib/tools.cpp -std=c++0x -lprimecount -o 501
